apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-app-stg
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
    spec:
      serviceAccountName: hello-app-stg@concise-faculty-406010.iam.gserviceaccount.com
      containers:
        - name: hello-app
          image: hello-app
          env:
            - name: NAME
              value: "stg"
