apiVersion: v1
kind: Service
metadata:
  name: esp-grpc-bookstore
spec:
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
      name: http2
  selector:
    app: esp-grpc-bookstore
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-grpc-bookstore
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-grpc-bookstore
    spec:
      containers:
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
            "--http2_port=9000",
            "--service=bookstore.endpoints.locari-dev.cloud.goog",
            "--version=2017-12-13r0",
            "--backend=grpc://127.0.0.1:8000"
          ]
          ports:
            - containerPort: 9000
        - name: bookstore
          image: gcr.io/endpointsv2/python-grpc-bookstore-server:1
          ports:
            - containerPort: 8000
